 const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    RENDERTODOS: 'RENDERTODOS'
}

export default ActionTypes;
